[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "att"
version = "0.1.0"
description = "attention mechanism implementation package"
readme = "README.md"
authors = [
    { name = "jayarnim", email = "jayarnim727@email.com" }
]
urls = { Homepage = "https://github.com/jayarnim/pkg-att" }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]